#!perl
use 5.14.1;

# I used this to deal with some people who canceled their service but still had
# invoices.  The invoices couldn't be dunned, because the expiration date
# couldn't be computed, because it tries to find active service.
#
# The invoices *shouldn't* have been dunned, though, because they won't be
# paid.  It won't happen with no cancelations because consumers will abandon
# their charges when they terminate.
#
# This might come up again, though, with other consumers still in the system.
# -- rjbs, 2012-05-17

use Moonpig;
use Pobox::Moonpig::Env;

my $guid = '20DDD266-9EA1-11E1-BC6D-510C77C542B6';
my $xid  = 'pobox:bg:65650459';

Moonpig->env->storage->do_rw_with_ledger(
  $guid,
  sub {
    my ($ledger) = @_;
    say $ledger->amount_due;
    my $consumer = $ledger->active_consumer_for_xid($xid);
    $consumer->replacement->reinvoice_initial_charges;
    $ledger->heartbeat;
    say $ledger->amount_due;
    die "DO NOT COMMIT\n";
  }
);

