#!perl
use 5.14.1;

use Moonpig;
use Moonpig::Util qw(to_dollars);
use Pobox::Moonpig;

my @credit;

Moonpig->env->storage->do_with_each_ledger(
  { ro => 1 },
  sub {
    my ($ledger) = @_;
    my @invoices = $ledger->invoices_without_quotes;
    for my $invoice (@invoices) {
      next if $invoice->is_abandoned;
      next unless grep { $_->description =~ /Shortfall/ } $invoice->all_charges;
      printf "%s - %s - %s\n",
        $ledger->short_ident,
        $invoice->guid,
        $invoice->created_at;
    }
  }
);

