#!/usr/bin/env perl
# -*- cperl -*-

use lib qw(lib eg/fauxbox/lib);
use Moonpig;
use Moonpig::App::Ob;
use Data::Dumper;
use Getopt::Std;

my $ob = Moonpig::App::Ob->new()->parse_ARGV(\@ARGV);
$ob->run;
